const DB_BASE = "https://bale-house-rental-default-rtdb.firebaseio.com";
const SETTINGS_CACHE_PREFIX = "gojo-register-settings:";

export const DEFAULT_TEMPLATE_SETTINGS = {
  idCardTitle: "Student ID Card",
  enrollmentLetterTitle: "Enrollment Letter",
  transferLetterTitle: "Transfer Letter",
  certificateTitle: "Student Certificate",
  signatoryName: "Registrar Office",
  footerNote: "Generated by Gojo Register Portal",
};

export const DEFAULT_PREFERENCES = {
  language: "English",
  timeZone: "Africa/Addis_Ababa",
  dateFormat: "YYYY-MM-DD",
  defaultPage: "/dashboard",
  emailNotifications: true,
  systemAlerts: true,
  deadlineReminders: true,
  registrationAlerts: true,
};

export const PERMISSION_LABELS = {
  viewDashboard: "View dashboard",
  manageStudents: "Manage students",
  manageParents: "Manage parents",
  manageTeachers: "Manage teachers",
  manageRegisterers: "Manage registerers",
  manageDocuments: "Manage documents",
  manageSettings: "Manage settings",
  manageBackups: "Manage backups",
};

export const MANAGED_ROLES = ["registerer", "registrar", "supervisor"];

export const DEFAULT_ROLE_PERMISSIONS = {
  registerer: {
    viewDashboard: true,
    manageStudents: true,
    manageParents: true,
    manageTeachers: false,
    manageRegisterers: false,
    manageDocuments: true,
    manageSettings: false,
    manageBackups: false,
  },
  registrar: {
    viewDashboard: true,
    manageStudents: true,
    manageParents: true,
    manageTeachers: true,
    manageRegisterers: true,
    manageDocuments: true,
    manageSettings: true,
    manageBackups: true,
  },
  supervisor: {
    viewDashboard: true,
    manageStudents: true,
    manageParents: true,
    manageTeachers: true,
    manageRegisterers: true,
    manageDocuments: true,
    manageSettings: true,
    manageBackups: true,
  },
};

function safeParse(value) {
  if (!value) return null;

  try {
    return JSON.parse(value);
  } catch {
    return null;
  }
}

function normalizeRole(role) {
  const normalized = String(role || "registerer").trim().toLowerCase();

  if (normalized === "admin") return "registrar";
  if (normalized === "school_admin") return "registrar";
  if (normalized === "register") return "registerer";
  if (MANAGED_ROLES.includes(normalized)) return normalized;

  return "registerer";
}

function getCacheKey(schoolCode) {
  return `${SETTINGS_CACHE_PREFIX}${schoolCode || "default"}`;
}

function getStorage() {
  if (typeof window === "undefined" || !window.localStorage) {
    return null;
  }

  return window.localStorage;
}

function mergeRolePermissions(permissions) {
  const nextPermissions = { ...DEFAULT_ROLE_PERMISSIONS };

  Object.entries(permissions || {}).forEach(([role, rolePermissions]) => {
    const normalizedRole = normalizeRole(role);
    nextPermissions[normalizedRole] = {
      ...(nextPermissions[normalizedRole] || {}),
      ...(rolePermissions || {}),
    };
  });

  return nextPermissions;
}

function normalizeSettings(source) {
  const settingsSource = source?.settings && typeof source.settings === "object" ? source.settings : source || {};

  return {
    academic: {
      sectionNamingSystem: settingsSource?.academic?.sectionNamingSystem || "Alphabetical (A, B, C)",
      promotionPassMark: Number(settingsSource?.academic?.promotionPassMark || 50),
      maxStudentsPerSection: Number(settingsSource?.academic?.maxStudentsPerSection || 45),
    },
    documentTemplates: {
      ...DEFAULT_TEMPLATE_SETTINGS,
      ...(settingsSource?.documentTemplates || {}),
    },
    preferences: {
      ...DEFAULT_PREFERENCES,
      ...(settingsSource?.preferences || {}),
    },
    permissions: mergeRolePermissions(settingsSource?.permissions),
    security: {
      sessionTimeout: Number(settingsSource?.security?.sessionTimeout || 30),
      twoFactorEnabled: Boolean(settingsSource?.security?.twoFactorEnabled),
      twoFactorSecret: String(settingsSource?.security?.twoFactorSecret || ""),
      twoFactorRecoveryCodes: Array.isArray(settingsSource?.security?.twoFactorRecoveryCodes)
        ? settingsSource.security.twoFactorRecoveryCodes
        : [],
    },
  };
}

export function buildSchoolRoot(schoolCode) {
  if (!schoolCode) return DB_BASE;
  return `${DB_BASE}/Platform1/Schools/${schoolCode}`;
}

export function readStoredRegistrar() {
  const storage = getStorage();

  if (!storage) return {};

  const registrar = safeParse(storage.getItem("registrar"));
  const admin = safeParse(storage.getItem("admin"));
  const session = registrar || admin || {};

  return {
    ...admin,
    ...registrar,
    ...session,
    role: normalizeRole(session.role || registrar?.role || admin?.role),
  };
}

export function persistStoredSession(updatedAdmin) {
  const storage = getStorage();

  if (!storage) return;

  const currentRegistrar = safeParse(storage.getItem("registrar")) || {};
  const currentAdmin = safeParse(storage.getItem("admin")) || {};
  const normalizedRole = normalizeRole(updatedAdmin?.role || currentRegistrar.role || currentAdmin.role);

  const nextRegistrar = {
    ...currentRegistrar,
    ...updatedAdmin,
    role: normalizedRole,
  };

  const nextAdmin = {
    ...currentAdmin,
    adminId: updatedAdmin?.adminId || currentAdmin.adminId || nextRegistrar.adminId || nextRegistrar.registrarId || null,
    userId: updatedAdmin?.userId || currentAdmin.userId || nextRegistrar.userId || null,
    name: updatedAdmin?.name || currentAdmin.name || nextRegistrar.name || "",
    profileImage: updatedAdmin?.profileImage || currentAdmin.profileImage || nextRegistrar.profileImage || "",
    schoolCode: updatedAdmin?.schoolCode || currentAdmin.schoolCode || nextRegistrar.schoolCode || "",
    username: updatedAdmin?.username || currentAdmin.username || nextRegistrar.username || "",
    role: normalizedRole,
  };

  storage.setItem("registrar", JSON.stringify(nextRegistrar));
  storage.setItem("admin", JSON.stringify(nextAdmin));
}

export function getUserRole(user) {
  return normalizeRole(user?.role || user?.userType || user?.accountType || "registerer");
}

export function getCachedSchoolSettings(schoolCode) {
  const storage = getStorage();

  if (!storage) {
    return normalizeSettings({});
  }

  const cachedValue = safeParse(storage.getItem(getCacheKey(schoolCode)));
  return normalizeSettings(cachedValue || {});
}

export function cacheSchoolSettings(schoolCode, settingsPatch) {
  const storage = getStorage();
  const normalized = normalizeSettings(settingsPatch);

  if (storage && schoolCode) {
    storage.setItem(getCacheKey(schoolCode), JSON.stringify(normalized));
  }

  return normalized;
}

export function formatDateForSettings(dateLike, preferences = DEFAULT_PREFERENCES) {
  if (!dateLike) return "Not available";

  const date = new Date(dateLike);

  if (Number.isNaN(date.getTime())) {
    return "Not available";
  }

  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  const format = preferences?.dateFormat || DEFAULT_PREFERENCES.dateFormat;

  if (format === "DD/MM/YYYY") {
    return `${day}/${month}/${year}`;
  }

  if (format === "MM/DD/YYYY") {
    return `${month}/${day}/${year}`;
  }

  return `${year}-${month}-${day}`;
}